### ISSUE TITLE
Failed to activate the touch-bar-utility package

### ISSUE THREAD

**Issue by davidlondono** [inakineitor/touch-bar-utility#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [touch-bar-utility](https://github.com/inakineitor/touch-bar-utility) package 1.0.3

### Stack Trace

Failed to activate the touch-bar-utility package

```
At Cannot read property 'buttonLabel' of undefined

TypeError: Cannot read property 'buttonLabel' of undefined
    at /packages/touch-bar-utility/lib/touch-bar-utility.js:57:55
    at Array.forEach (native)
    at /packages/touch-bar-utility/lib/touch-bar-utility.js:52:14
    at Object.activate (/packages/touch-bar-utility/lib/touch-bar-utility.js:85:53)
    at Package.module.exports.Package.activateNow (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /private/var/folders/k2/tlmg40bj7fgc560pqlszjkrm0000gn/T/AppTranslocation/27B411D5-FA85-4D88-AC53-BFC0DBF0AD73/d/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.1.0 
build-npm-apm 0.12.0 
busy-signal 1.4.3 
ctags-status 1.3.7 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.4 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
minimap 4.29.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.2 
minimap-selection 4.4.0 
npm-plus 0.4.0 
platformio-ide-terminal 2.5.3 
pristine-ui 1.1.6 
project-manager 3.3.5 
remote-atom 1.3.10 
script 3.15.0 
sync-settings 0.8.2 
touch-bar-utility 1.0.3 
tree-view-git-status 1.4.0 
```

**Comment by inakineitor** [comment]
Could you please try again with version 1.0.5. I recently updated the package and fixed a few bugs.
