### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by david-pivonka** [inakineitor/touch-bar-utility#3]
[Enter steps to reproduce:]

1. Start Atom Beta
2. Error message popup

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [touch-bar-utility](https://github.com/inakineitor/touch-bar-utility) package 2.0.0

### Stack Trace

Failed to load the touch-bar-utility package

```
At /Users/davidpivonka/.atom/packages/touch-bar-utility/lib/touch-bar-utility.js: Unexpected token (211:52)

SyntaxError: /Users/davidpivonka/.atom/packages/touch-bar-utility/lib/touch-bar-utility.js: Unexpected token (211:52)
            icon: NativeImage.createFromPath(element.pathOfIcon),
            iconPosition: element.iconPosition,
            click: element.clickDispatchAction ? () dispatchelement.clickDispatchAction : element.click // The clickDispatchAction will override the function of the 'click' element
          });
          break;

    at Parser.pp.raise (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.parseParenAndDistinguishExpression (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:974:14)
    at Parser.pp.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:378:19)
    at Parser.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:150:28)
    at Parser.pp.parseMaybeAssign (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseObjPropValue (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:652:99)
    at Parser.parseObjPropValue (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:891:13)
    at Parser.pp.parseObj (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:640:10)
    at Parser.pp.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:392:19)
    at Parser.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExprListItem (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:819:24)
    at Parser.pp.parseExprList (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseNew (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:545:27)
    at Parser.pp.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:408:19)
    at Parser.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:236:19)
```

### Commands

```
     -0:03.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-spotify2 2.1.2 
autoprefixer 3.7.1 
busy-signal 1.4.3 
duotone-dark-sky-syntax 2.1.0 
emmet 2.4.3 
file-icons 2.1.9 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-autohider 1.5.3 
minimap-linter 2.0.2 
pristine-ui 1.1.6 
Remote-FTP 1.1.3 
touch-bar-utility 2.0.0 
```

**Comment by inakineitor** [comment]
I don't currently have a MacBook Pro, I am developing from a Windows machine. I think I found the bug and removed it, but can't be sure because I can't run the code. I updated the package to version 2.0.1. If the bug persists, please tell me what is the new error that appears.

**Comment by david-pivonka** [comment]
It's still not working

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [touch-bar-utility](https://github.com/inakineitor/touch-bar-utility) package 2.0.1


### Stack Trace

Failed to load the touch-bar-utility package

```
At /Users/davidpivonka/.atom/packages/touch-bar-utility/lib/touch-bar-utility.js: Unexpected token (216:167)

SyntaxError: /Users/davidpivonka/.atom/packages/touch-bar-utility/lib/touch-bar-utility.js: Unexpected token (216:167)

        case 'color-picker':
          if(element.availableColors && (!(element.availableColors instanceof Array) || !(element.availableColors.every(function(i){ return typeof i === "string" }))) return callback(new Error("The color-picker's availableColors must be a string of arrays"));
          if(element.selectedColor && typeof element.selectedColor !== 'string') return callback(new Error("The color-picker's selectedColor must be a string"));
          if(element.change && typeof element.change !== 'function') return callback(new Error("The color-picker's change must be a function"));

    at Parser.pp.raise (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.expect (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/util.js:76:33)
    at Parser.pp.parseParenExpression (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:440:8)
    at Parser.pp.parseIfStatement (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:267:20)
    at Parser.pp.parseStatement (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:87:19)
    at Parser.parseStatement (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseSwitchStatement (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:322:32)
    at Parser.pp.parseStatement (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:91:19)
    at Parser.parseStatement (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseFunction (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/statement.js:524:8)
    at Parser.pp.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:397:19)
    at Parser.parseExprAtom (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExprListItem (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:801:16)
    at Parser.parseExprListItem (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/plugins/flow.js:819:24)
    at Parser.pp.parseExprList (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:789:20)
    at Parser.pp.parseSubscripts (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:270:29)
    at Parser.pp.parseExprSubscripts (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:240:17)
    at Parser.pp.parseMaybeUnary (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/babylon/lib/parser/expression.js:112:19)
```

### Commands

```
     -0:02.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-spotify2 2.1.2 
autoprefixer 3.7.1 
block-comment 0.4.3 
busy-signal 1.4.3 
duotone-dark-sky-syntax 2.1.0 
emmet 2.4.3 
file-icons 2.1.9 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-tidy 2.3.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-autohider 1.5.3 
minimap-linter 2.0.2 
pristine-ui 1.1.6 
Remote-FTP 1.1.3 
touch-bar-utility 2.0.1 
```

**Comment by inakineitor** [comment]
The error that nows appear is from another line. That means that the first error was fixed. <strong>Yay!</strong>
I fixed the new error and updated the package to v2.0.2
Could you please try again and tell me if there are any more errors please?

**Comment by david-pivonka** [comment]
Now it's just this: [http://i.imgur.com/qG9oHoF.png](http://i.imgur.com/qG9oHoF.png).
btw. thank you for your support ☺️

**Comment by inakineitor** [comment]
There was an error caused by a variable name mismatch. Fixed it and updated to 2.0.3.

**Comment by david-pivonka** [comment]
<img width="498" alt="obrazek aplikace zpravy 3194620157" src="https://user-images.githubusercontent.com/4690621/28753876-dd430b0e-753a-11e7-970c-9ad5c1fe5715.png">

**Comment by inakineitor** [comment]
I found an error that caused an unexpected token at position 2 and fixed it. You should update to version 2.0.6, but your error is caused by something else. I think it is the configuration of the package.

¿Could you please tell me what you have in the configuration?
It should look like this:
![image](https://user-images.githubusercontent.com/7718934/28755003-d9caf90e-7527-11e7-9e4f-198982d4d1d5.png)

**Comment by david-pivonka** [comment]
Aw, sorry, my bad. I was using old syntax from version 1, but it's still not working even with `[{"type": "button", "label": "Beautify Editor", "clickDispatchAction": "atom-beautify:beautify-editor"}]`
<img width="494" alt="obrazek aplikace zpravy 4163524852" src="https://user-images.githubusercontent.com/4690621/28755231-66840f4c-7556-11e7-90e1-c613b6feec59.png">

**Comment by inakineitor** [comment]
I think I have fixed. The current version is 2.0.7

**Comment by david-pivonka** [comment]
<img width="500" alt="image 2017-07-30 at 7 26 28 odp" src="https://user-images.githubusercontent.com/4690621/28755514-27719656-755d-11e7-885f-00915b50660f.png">

**Comment by inakineitor** [comment]
Added conditional before creating icon. New version is 2.0.8

**Comment by david-pivonka** [comment]
Now it shows button on touchbar, but this error occurs:
<img width="1206" alt="image 2017-07-30 at 8 03 09 odp" src="https://user-images.githubusercontent.com/4690621/28755758-39a617c0-7562-11e7-8fa3-08d245531259.png">
`Active Editor not found. 
Hide Stack Trace
Error: Active Editor not found. 
    at /Users/davidpivonka/.atom/packages/atom-beautify/src/beautify.coffee:152:29
    at Promise._execute (/Users/davidpivonka/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/davidpivonka/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/davidpivonka/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at HTMLElement.beautify (/Users/davidpivonka/.atom/packages/atom-beautify/src/beautify.coffee:77:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:166:25)
    at PackageManager.activatePackage.then.NotificationManager.addFatalError.dismissable (/Users/davidpivonka/.atom/packages/touch-bar-utility/lib/touch-bar-utility.js:142:21)`

**Comment by inakineitor** [comment]
All the errors related to parsing seem to have been resolved. This error I think is caused by a problem in the triggering of other packages. I modified the function that is in charge of that and updated the package to version 2.0.9

**Comment by david-pivonka** [comment]
Yup, it's working. Thank you. 😊

**Comment by inakineitor** [comment]
You are welcome. For any other errors that you may find, please don't hesitate to create an issue.
